// Generates supabase/seed.sql from src/data/catalog.js so the DB and the catalogue never drift.
// seed.sql is applied only by `supabase db reset` (local/dev) — never to production automatically.
import { writeFileSync } from 'node:fs';
import { SEED_PRODUCTS, SEED_COUPONS } from '../src/data/catalog.js';

const q = v => v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const j = v => `${q(JSON.stringify(v))}::jsonb`;
const arr = a => `array[${(a || []).map(q).join(',')}]::text[]`;

let sql = '-- GENERATED by supabase/gen_seed.mjs from src/data/catalog.js — do not edit by hand.\n\n';
for (const p of SEED_PRODUCTS) {
  sql += `insert into public.products (id, sku, type, line, family, spaces, price, compare_at, stock, giftable, best_seller, aroma_deal, is_new, sizes, features, specs, ideal, notes, name, tagline, description, img, gallery) values (` +
    [q(p.id), q(p.sku), q(p.type), q(p.line || ''), q(p.family), arr(p.spaces), p.price, p.compareAt || 0, p.stock, p.giftable, !!p.bestSeller, !!p.aromaDeal, !!p.isNew,
     j(p.sizes), arr(p.features), j(p.specs || []), p.ideal ? j(p.ideal) : 'null', j(p.notes), j(p.name), j(p.tagline || {}), j(p.desc || {}), q(p.img), arr(p.gallery)].join(', ') + ');\n';
}
sql += '\n';
/* The production migration creates the launch codes inactive; local development switches them on. */
for (const c of SEED_COUPONS) sql += `insert into public.coupons (code, type, value, min_subtotal, min_exclusive, first_order_only, active, note) values (${q(c.code)}, ${q(c.type)}, ${c.value}, ${c.min}, ${!!c.minExclusive}, ${!!c.firstOrderOnly}, ${c.active}, ${q(c.note)}) on conflict (code) do update set active = excluded.active;\n`;

/* Local development accounts only (passwords are bcrypt-hashed by Postgres). */
const user = (id, email, pw, name, admin) => `
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-0000-0000-000000000000', '${id}', 'authenticated', 'authenticated', '${email}', crypt('${pw}', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]${admin ? ',"role":"admin"' : ''}}', '{"full_name":"${name}"}', now(), now(), '', '', '', '');
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '${id}', '${id}', '{"sub":"${id}","email":"${email}","email_verified":true}', 'email', now(), now(), now());`;
sql += '\n-- DEV ONLY accounts\n' + user('11111111-1111-1111-1111-111111111111', 'admin@ozonescents.com', 'Admin@123', 'Store Admin', true)
  + user('22222222-2222-2222-2222-222222222222', 'demo@ozonescents.com', 'Demo@123', 'Layla Hassan', false) + '\n';
sql += `insert into public.addresses (user_id, label, first_name, last_name, country, line1, city, state, phone, is_default)
values ('22222222-2222-2222-2222-222222222222', 'Home', 'Layla', 'Hassan', 'AE', 'Villa 12, Street 4', 'Sharjah', 'Al Majaz', '+971 50 123 4567', true);
insert into public.special_dates (user_id, occasion, person_name, date, timing) values ('22222222-2222-2222-2222-222222222222', 'birthday', 'Mum', '2026-11-18', 7);
insert into public.wishlist (user_id, product_id) values ('22222222-2222-2222-2222-222222222222', 'oil-zestora'), ('22222222-2222-2222-2222-222222222222', 'tower-diffuser');
`;
writeFileSync(new URL('./seed.sql', import.meta.url), sql);

/* catalog.sql: products ONLY — safe for a real project (no demo accounts, no test data).
   Re-running it never overwrites products already edited in the admin panel.
   Apply with: npx supabase db query --linked -f supabase/catalog.sql */
const catalog = '-- GENERATED by supabase/gen_seed.mjs — catalogue products for a production/staging database.\n' +
  sql.split('\n').filter(l => l.startsWith('insert into public.products')).map(l => l.replace(/\);$/, ') on conflict (id) do nothing;')).join('\n') + '\n';
writeFileSync(new URL('./catalog.sql', import.meta.url), catalog);
console.log('seed.sql written:', SEED_PRODUCTS.length, 'products');
