// GENERATED by scripts/bundle-functions.mjs from supabase/functions/public-forms — paste into the Supabase dashboard editor.
// Edit the source files, not this copy.
import { createClient, type SupabaseClient } from 'npm:@supabase/supabase-js@2';

/* Public forms behind a CAPTCHA (SEC-015, FR-CNT-001..004): contact messages and newsletter sign-ups.

   The browser can no longer call send_message / subscribe_newsletter directly (migration 20261005010000);
   requests come through here, where the Cloudflare Turnstile token is verified server-side first.
     TURNSTILE_SECRET_KEY set   → every request needs a valid token
                                  (a signed-in customer may join the newsletter without one: they already passed login)
     TURNSTILE_SECRET_KEY unset → no CAPTCHA check (local development only — always set it in production)
   The database functions keep their own rate limits and validation. */
/* Server-side order/payment helpers shared by payment providers (INT-PAY-001).

   A provider integration only has to:
     1. identify the order (and, for browser calls, the signed-in customer who owns it), and
     2. after the provider has VERIFIED the payment (signed webhook / API lookup), call markPaid()
        with the provider's reference — amount and currency always come from the database row.
   mark_order_paid() is idempotent and rejects amount/currency mismatches (BR-PAY-001..004). */

export type Order = { id: string; user_id: string; total: number; currency: string; access_token: string; status: string; payment_status: string };

export const ORDER_ID_RE = /^OZ\d{6,12}$/;
export const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function serviceClient(): SupabaseClient {
  return createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, { auth: { persistSession: false } });
}

/* The customer behind the request's JWT, or null (anon key / invalid / expired token) */
export async function requestUser(admin: SupabaseClient, req: Request): Promise<{ id: string } | null> {
  const jwt = (req.headers.get('authorization') || '').replace(/^Bearer\s+/i, '');
  if (!jwt) return null;
  const { data, error } = await admin.auth.getUser(jwt);
  return error || !data.user ? null : { id: data.user.id };
}

/* Load an order the caller is allowed to pay: it must belong to them and the secret token must match.
   Returns null for "not found", "not yours" and "wrong token" alike so order ids can't be probed. */
export async function orderForCustomer(admin: SupabaseClient, id: string, token: string, userId: string): Promise<Order | null> {
  const { data, error } = await admin.from('orders')
    .select('id, user_id, total, currency, access_token, status, payment_status').eq('id', id).maybeSingle();
  if (error) throw new Error('lookup failed');
  if (!data || data.user_id !== userId || data.access_token !== token) return null;
  return data as Order;
}

export async function markPaid(admin: SupabaseClient, o: Order, provider: string, ref: string) {
  const { error } = await admin.rpc('mark_order_paid', { p_id: o.id, p_provider: provider, p_ref: ref, p_amount: o.total, p_currency: o.currency });
  if (error) throw new Error('mark_order_paid: ' + error.message);
}

export async function markCancelled(admin: SupabaseClient, o: Order) {
  const { error } = await admin.rpc('mark_order_failed', { p_id: o.id, p_status: 'cancelled' });
  if (error) throw new Error('mark_order_failed: ' + error.message);
}

/* CORS limited to the configured storefront origins (SEC-019) */
export function corsHeaders(req: Request) {
  const origins = (Deno.env.get('ALLOWED_ORIGINS') ?? 'http://localhost:5173,http://localhost:4173').split(',').map(s => s.trim());
  const origin = req.headers.get('origin');
  return {
    'Access-Control-Allow-Origin': origin && origins.includes(origin) ? origin : origins[0],
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Vary': 'Origin'
  };
}

async function verifyTurnstile(token: unknown, ip: string | null): Promise<boolean> {
  const secret = Deno.env.get('TURNSTILE_SECRET_KEY');
  if (!secret) return true;
  if (typeof token !== 'string' || !token || token.length > 2048) return false;
  const body = new URLSearchParams({ secret, response: token });
  if (ip) body.set('remoteip', ip);
  const r = await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify', { method: 'POST', body });
  const j = await r.json().catch(() => ({}));
  return j.success === true;
}

const str = (v: unknown, max: number) => typeof v === 'string' && v.length <= max ? v : null;

Deno.serve(async req => {
  const headers = { ...corsHeaders(req), 'Content-Type': 'application/json' };
  const reply = (status: number, body: unknown) => new Response(JSON.stringify(body), { status, headers });
  if (req.method === 'OPTIONS') return new Response('ok', { headers });
  if (req.method !== 'POST') return reply(405, { error: 'method' });

  // deno-lint-ignore no-explicit-any
  let b: any;
  try { b = await req.json(); } catch { return reply(400, { error: 'invalidInput' }); }
  if (!b || (b.kind !== 'contact' && b.kind !== 'newsletter')) return reply(400, { error: 'invalidInput' });

  const admin = serviceClient();
  const ip = req.headers.get('cf-connecting-ip') ?? req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ?? null;
  const signedIn = b.kind === 'newsletter' && !b.captchaToken ? await requestUser(admin, req) : null;
  if (!signedIn && !(await verifyTurnstile(b.captchaToken, ip))) return reply(400, { error: 'captcha' });

  const mapErr = (msg: string) => /rate_limited/.test(msg) ? 'rate_limited' : /check constraint|violates|invalid/i.test(msg) ? 'invalidInput' : 'unknown';
  try {
    if (b.kind === 'contact') {
      const name = str(b.name, 100), email = str(b.email, 254), message = str(b.message, 2000);
      if (!name || !email || !message) return reply(400, { error: 'invalidInput' });
      const { error } = await admin.rpc('send_message', { p_name: name, p_email: email, p_phone: str(b.phone, 30) ?? '', p_topic: str(b.topic, 20) ?? 'general', p_message: message });
      if (error) return reply(error.message.includes('rate_limited') ? 429 : 400, { error: mapErr(error.message) });
    } else {
      const email = str(b.email, 254);
      if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)) return reply(400, { error: 'invalidInput' });
      const { error } = await admin.rpc('subscribe_newsletter', { p_email: email });
      if (error) return reply(error.message.includes('rate_limited') ? 429 : 400, { error: mapErr(error.message) });
    }
    return reply(200, { ok: true });
  } catch (e) {
    console.error('public-forms', b.kind, (e as Error).message);
    return reply(500, { error: 'unknown' });
  }
});

