// GENERATED by scripts/bundle-functions.mjs from supabase/functions/stripe-webhook — paste into the Supabase dashboard editor.
// Edit the source files, not this copy.
import { createClient, type SupabaseClient } from 'npm:@supabase/supabase-js@2';

/* Stripe webhook (SYS-02, INT-PAY-005/006, FR-PAY-005..012).

   Every event is signature-verified (STRIPE_WEBHOOK_SECRET) before anything happens (SEC-008).
   Paid  : checkout.session.completed (payment_status=paid) / checkout.session.async_payment_succeeded
           → amount + currency checked against the database row, then mark_order_paid (idempotent, BR-PAY-002..004)
   Failed: checkout.session.expired / async_payment_failed → order cancelled + stock released,
           but ONLY if it is the order's current session (a retry's old session can't cancel the order)
   Refund: charge.refunded (full refund) → order marked refunded
   Unknown orders, other events and duplicates are acknowledged with 200 so Stripe stops retrying. */
/* Server-side order/payment helpers shared by payment providers (INT-PAY-001).

   A provider integration only has to:
     1. identify the order (and, for browser calls, the signed-in customer who owns it), and
     2. after the provider has VERIFIED the payment (signed webhook / API lookup), call markPaid()
        with the provider's reference — amount and currency always come from the database row.
   mark_order_paid() is idempotent and rejects amount/currency mismatches (BR-PAY-001..004). */

export type Order = { id: string; user_id: string; total: number; currency: string; access_token: string; status: string; payment_status: string };

export const ORDER_ID_RE = /^OZ\d{6,12}$/;
export const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function serviceClient(): SupabaseClient {
  return createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, { auth: { persistSession: false } });
}

/* The customer behind the request's JWT, or null (anon key / invalid / expired token) */
export async function requestUser(admin: SupabaseClient, req: Request): Promise<{ id: string } | null> {
  const jwt = (req.headers.get('authorization') || '').replace(/^Bearer\s+/i, '');
  if (!jwt) return null;
  const { data, error } = await admin.auth.getUser(jwt);
  return error || !data.user ? null : { id: data.user.id };
}

/* Load an order the caller is allowed to pay: it must belong to them and the secret token must match.
   Returns null for "not found", "not yours" and "wrong token" alike so order ids can't be probed. */
export async function orderForCustomer(admin: SupabaseClient, id: string, token: string, userId: string): Promise<Order | null> {
  const { data, error } = await admin.from('orders')
    .select('id, user_id, total, currency, access_token, status, payment_status').eq('id', id).maybeSingle();
  if (error) throw new Error('lookup failed');
  if (!data || data.user_id !== userId || data.access_token !== token) return null;
  return data as Order;
}

export async function markPaid(admin: SupabaseClient, o: Order, provider: string, ref: string) {
  const { error } = await admin.rpc('mark_order_paid', { p_id: o.id, p_provider: provider, p_ref: ref, p_amount: o.total, p_currency: o.currency });
  if (error) throw new Error('mark_order_paid: ' + error.message);
}

export async function markCancelled(admin: SupabaseClient, o: Order) {
  const { error } = await admin.rpc('mark_order_failed', { p_id: o.id, p_status: 'cancelled' });
  if (error) throw new Error('mark_order_failed: ' + error.message);
}

/* CORS limited to the configured storefront origins (SEC-019) */
export function corsHeaders(req: Request) {
  const origins = (Deno.env.get('ALLOWED_ORIGINS') ?? 'http://localhost:5173,http://localhost:4173').split(',').map(s => s.trim());
  const origin = req.headers.get('origin');
  return {
    'Access-Control-Allow-Origin': origin && origins.includes(origin) ? origin : origins[0],
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Vary': 'Origin'
  };
}

/* Minimal Stripe client for Edge Functions (no SDK): REST calls + webhook signature verification.
   Secrets come from function secrets only: STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET (SEC-006/018). */

const API = 'https://api.stripe.com/v1';

/* Stripe expects form encoding with bracket notation: a[b][0][c]=d */
export function form(obj: Record<string, unknown>, prefix = ''): string[] {
  const out: string[] = [];
  for (const [k, v] of Object.entries(obj)) {
    if (v === undefined || v === null) continue;
    const key = prefix ? `${prefix}[${k}]` : k;
    if (typeof v === 'object') out.push(...form(v as Record<string, unknown>, key));
    else out.push(`${encodeURIComponent(key)}=${encodeURIComponent(String(v))}`);
  }
  return out;
}

export async function stripe(path: string, params: Record<string, unknown> = {}, opts: { method?: string; idempotencyKey?: string } = {}) {
  const key = Deno.env.get('STRIPE_SECRET_KEY');
  if (!key) throw new Error('STRIPE_SECRET_KEY not set');
  const method = opts.method ?? 'POST';
  const body = method === 'GET' ? undefined : form(params).join('&');
  const r = await fetch(`${API}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${key}`,
      'Content-Type': 'application/x-www-form-urlencoded',
      'Stripe-Version': '2024-06-20',
      ...(opts.idempotencyKey ? { 'Idempotency-Key': opts.idempotencyKey } : {})
    },
    body
  });
  const json = await r.json();
  if (!r.ok) throw new Error(`stripe ${r.status}: ${json?.error?.type ?? ''} ${json?.error?.message ?? ''}`.trim());
  return json;
}

/* AED (and most currencies) use 2 decimals: AED 250.00 → 25000 fils */
export const toMinor = (amount: number) => Math.round(Number(amount) * 100);

const enc = new TextEncoder();
function timingSafeEqual(a: string, b: string) {
  if (a.length !== b.length) return false;
  let d = 0;
  for (let i = 0; i < a.length; i++) d |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return d === 0;
}

/* Verify the Stripe-Signature header (t=timestamp,v1=hmac). Rejects stale events (replay protection). */
export async function verifyStripeSignature(payload: string, header: string | null, secret: string, toleranceSec = 300): Promise<boolean> {
  if (!header || !secret) return false;
  const parts = Object.fromEntries(header.split(',').map(p => p.split('=')).filter(x => x.length === 2).map(([k, v]) => [k.trim(), v.trim()]));
  const sigs = header.split(',').map(p => p.trim()).filter(p => p.startsWith('v1=')).map(p => p.slice(3));
  const t = Number(parts.t);
  if (!t || !sigs.length) return false;
  if (Math.abs(Date.now() / 1000 - t) > toleranceSec) return false;
  const k = await crypto.subtle.importKey('raw', enc.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  const mac = new Uint8Array(await crypto.subtle.sign('HMAC', k, enc.encode(`${t}.${payload}`)));
  const hex = [...mac].map(b => b.toString(16).padStart(2, '0')).join('');
  return sigs.some(s => timingSafeEqual(s, hex));
}

const ok = (body: unknown = { received: true }) => new Response(JSON.stringify(body), { status: 200, headers: { 'Content-Type': 'application/json' } });

Deno.serve(async req => {
  if (req.method !== 'POST') return new Response('method', { status: 405 });
  const secret = Deno.env.get('STRIPE_WEBHOOK_SECRET') ?? '';
  const payload = await req.text();
  if (!(await verifyStripeSignature(payload, req.headers.get('stripe-signature'), secret))) {
    console.error('stripe-webhook: invalid signature');                    // OBS-003
    return new Response('invalid signature', { status: 400 });
  }

  // deno-lint-ignore no-explicit-any
  let event: any;
  try { event = JSON.parse(payload); } catch { return new Response('bad json', { status: 400 }); }
  const obj = event?.data?.object ?? {};
  const admin = serviceClient();

  const loadOrder = async (id: string | undefined) => {
    if (!id) return null;
    const { data } = await admin.from('orders').select('id, total, currency, status, payment_status, payment_session_id').eq('id', id).maybeSingle();
    return data;
  };

  try {
    switch (event.type) {
      case 'checkout.session.completed':
      case 'checkout.session.async_payment_succeeded': {
        if (obj.payment_status !== 'paid') return ok({ ignored: 'not paid yet' });   // async methods confirm later
        const order = await loadOrder(obj.metadata?.order_id ?? obj.client_reference_id);
        if (!order) { console.error('stripe-webhook: unknown order', obj.id); return ok({ ignored: 'unknown order' }); }
        if (order.payment_status === 'paid') return ok({ duplicate: true });
        if (obj.amount_total !== toMinor(order.total) || String(obj.currency).toUpperCase() !== order.currency) {
          console.error('stripe-webhook: amount/currency mismatch', order.id, obj.amount_total, obj.currency);
          return ok({ ignored: 'amount mismatch' });                            // never mark paid; flagged in logs for review
        }
        const ref = typeof obj.payment_intent === 'string' ? obj.payment_intent : obj.id;
        const { error } = await admin.rpc('mark_order_paid', { p_id: order.id, p_provider: 'stripe', p_ref: ref, p_amount: order.total, p_currency: order.currency });
        if (error) {
          /* paid after the order was cancelled/expired: money was taken but the order can't be fulfilled → needs a refund */
          console.error('stripe-webhook: could not mark paid — REFUND REQUIRED', order.id, ref, error.message);
          return ok({ attention: 'refund required' });
        }
        return ok({ paid: order.id });
      }
      case 'checkout.session.expired':
      case 'checkout.session.async_payment_failed': {
        const order = await loadOrder(obj.metadata?.order_id ?? obj.client_reference_id);
        if (!order || order.payment_session_id !== obj.id) return ok({ ignored: 'stale session' });
        await admin.rpc('mark_order_failed', { p_id: order.id, p_status: event.type.endsWith('failed') ? 'failed' : 'cancelled' });
        return ok({ cancelled: order.id });
      }
      case 'charge.refunded': {
        if (!obj.refunded) return ok({ ignored: 'partial refund' });               // partial refunds are handled manually
        let order = await loadOrder(obj.metadata?.order_id);
        if (!order && typeof obj.payment_intent === 'string') {               // we store the PaymentIntent id as payment_ref
          const { data } = await admin.from('orders').select('id').eq('payment_ref', obj.payment_intent).maybeSingle();
          order = await loadOrder(data?.id);
        }
        if (!order) return ok({ ignored: 'unknown order' });
        const { error } = await admin.rpc('mark_order_refunded', { p_id: order.id, p_ref: obj.id });
        if (error) console.error('stripe-webhook: refund sync failed', order.id, error.message);
        return ok({ refunded: order.id });
      }
      default:
        return ok({ ignored: event.type });
    }
  } catch (e) {
    console.error('stripe-webhook', event?.type, (e as Error).message);
    return new Response('error', { status: 500 });                               // Stripe retries with backoff
  }
});

