// GENERATED by scripts/bundle-functions.mjs from supabase/functions/stripe-checkout — paste into the Supabase dashboard editor.
// Edit the source files, not this copy.
import { createClient, type SupabaseClient } from 'npm:@supabase/supabase-js@2';

/* Creates a Stripe Checkout Session for an order the signed-in customer owns (INT-PAY-002/004).

   The amount and currency come from the database row created by create_order() — never from the browser.
   The customer pays on Stripe's hosted page, so card data never reaches this site (FR-PAY-003/004).
   The order is marked paid only by the signature-verified webhook (stripe-webhook), not by this redirect. */
/* Server-side order/payment helpers shared by payment providers (INT-PAY-001).

   A provider integration only has to:
     1. identify the order (and, for browser calls, the signed-in customer who owns it), and
     2. after the provider has VERIFIED the payment (signed webhook / API lookup), call markPaid()
        with the provider's reference — amount and currency always come from the database row.
   mark_order_paid() is idempotent and rejects amount/currency mismatches (BR-PAY-001..004). */

export type Order = { id: string; user_id: string; total: number; currency: string; access_token: string; status: string; payment_status: string };

export const ORDER_ID_RE = /^OZ\d{6,12}$/;
export const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function serviceClient(): SupabaseClient {
  return createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, { auth: { persistSession: false } });
}

/* The customer behind the request's JWT, or null (anon key / invalid / expired token) */
export async function requestUser(admin: SupabaseClient, req: Request): Promise<{ id: string } | null> {
  const jwt = (req.headers.get('authorization') || '').replace(/^Bearer\s+/i, '');
  if (!jwt) return null;
  const { data, error } = await admin.auth.getUser(jwt);
  return error || !data.user ? null : { id: data.user.id };
}

/* Load an order the caller is allowed to pay: it must belong to them and the secret token must match.
   Returns null for "not found", "not yours" and "wrong token" alike so order ids can't be probed. */
export async function orderForCustomer(admin: SupabaseClient, id: string, token: string, userId: string): Promise<Order | null> {
  const { data, error } = await admin.from('orders')
    .select('id, user_id, total, currency, access_token, status, payment_status').eq('id', id).maybeSingle();
  if (error) throw new Error('lookup failed');
  if (!data || data.user_id !== userId || data.access_token !== token) return null;
  return data as Order;
}

export async function markPaid(admin: SupabaseClient, o: Order, provider: string, ref: string) {
  const { error } = await admin.rpc('mark_order_paid', { p_id: o.id, p_provider: provider, p_ref: ref, p_amount: o.total, p_currency: o.currency });
  if (error) throw new Error('mark_order_paid: ' + error.message);
}

export async function markCancelled(admin: SupabaseClient, o: Order) {
  const { error } = await admin.rpc('mark_order_failed', { p_id: o.id, p_status: 'cancelled' });
  if (error) throw new Error('mark_order_failed: ' + error.message);
}

/* CORS limited to the configured storefront origins (SEC-019) */
export function corsHeaders(req: Request) {
  const origins = (Deno.env.get('ALLOWED_ORIGINS') ?? 'http://localhost:5173,http://localhost:4173').split(',').map(s => s.trim());
  const origin = req.headers.get('origin');
  return {
    'Access-Control-Allow-Origin': origin && origins.includes(origin) ? origin : origins[0],
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Vary': 'Origin'
  };
}

/* Minimal Stripe client for Edge Functions (no SDK): REST calls + webhook signature verification.
   Secrets come from function secrets only: STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET (SEC-006/018). */

const API = 'https://api.stripe.com/v1';

/* Stripe expects form encoding with bracket notation: a[b][0][c]=d */
export function form(obj: Record<string, unknown>, prefix = ''): string[] {
  const out: string[] = [];
  for (const [k, v] of Object.entries(obj)) {
    if (v === undefined || v === null) continue;
    const key = prefix ? `${prefix}[${k}]` : k;
    if (typeof v === 'object') out.push(...form(v as Record<string, unknown>, key));
    else out.push(`${encodeURIComponent(key)}=${encodeURIComponent(String(v))}`);
  }
  return out;
}

export async function stripe(path: string, params: Record<string, unknown> = {}, opts: { method?: string; idempotencyKey?: string } = {}) {
  const key = Deno.env.get('STRIPE_SECRET_KEY');
  if (!key) throw new Error('STRIPE_SECRET_KEY not set');
  const method = opts.method ?? 'POST';
  const body = method === 'GET' ? undefined : form(params).join('&');
  const r = await fetch(`${API}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${key}`,
      'Content-Type': 'application/x-www-form-urlencoded',
      'Stripe-Version': '2024-06-20',
      ...(opts.idempotencyKey ? { 'Idempotency-Key': opts.idempotencyKey } : {})
    },
    body
  });
  const json = await r.json();
  if (!r.ok) throw new Error(`stripe ${r.status}: ${json?.error?.type ?? ''} ${json?.error?.message ?? ''}`.trim());
  return json;
}

/* AED (and most currencies) use 2 decimals: AED 250.00 → 25000 fils */
export const toMinor = (amount: number) => Math.round(Number(amount) * 100);

const enc = new TextEncoder();
function timingSafeEqual(a: string, b: string) {
  if (a.length !== b.length) return false;
  let d = 0;
  for (let i = 0; i < a.length; i++) d |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return d === 0;
}

/* Verify the Stripe-Signature header (t=timestamp,v1=hmac). Rejects stale events (replay protection). */
export async function verifyStripeSignature(payload: string, header: string | null, secret: string, toleranceSec = 300): Promise<boolean> {
  if (!header || !secret) return false;
  const parts = Object.fromEntries(header.split(',').map(p => p.split('=')).filter(x => x.length === 2).map(([k, v]) => [k.trim(), v.trim()]));
  const sigs = header.split(',').map(p => p.trim()).filter(p => p.startsWith('v1=')).map(p => p.slice(3));
  const t = Number(parts.t);
  if (!t || !sigs.length) return false;
  if (Math.abs(Date.now() / 1000 - t) > toleranceSec) return false;
  const k = await crypto.subtle.importKey('raw', enc.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  const mac = new Uint8Array(await crypto.subtle.sign('HMAC', k, enc.encode(`${t}.${payload}`)));
  const hex = [...mac].map(b => b.toString(16).padStart(2, '0')).join('');
  return sigs.some(s => timingSafeEqual(s, hex));
}

const SITE_URL = (Deno.env.get('SITE_URL') ?? 'http://localhost:5173').replace(/\/+$/, '');
const LOCALES: Record<string, string> = { en: 'en', es: 'es', ar: 'auto' };   // Stripe Checkout has no Arabic UI yet

Deno.serve(async req => {
  const headers = { ...corsHeaders(req), 'Content-Type': 'application/json' };
  const reply = (status: number, body: unknown) => new Response(JSON.stringify(body), { status, headers });
  if (req.method === 'OPTIONS') return new Response('ok', { headers });
  if (req.method !== 'POST') return reply(405, { error: 'method' });
  if (!Deno.env.get('STRIPE_SECRET_KEY')) return reply(503, { error: 'paymentsUnavailable' });

  let body: { order_id?: unknown; token?: unknown };
  try { body = await req.json(); } catch { return reply(400, { error: 'invalidInput' }); }
  const { order_id, token } = body;
  if (typeof order_id !== 'string' || !ORDER_ID_RE.test(order_id) || typeof token !== 'string' || !UUID_RE.test(token)) return reply(400, { error: 'invalidInput' });

  try {
    const admin = serviceClient();
    const user = await requestUser(admin, req);
    if (!user) return reply(401, { error: 'authRequired' });
    const order = await orderForCustomer(admin, order_id, token, user.id);
    if (!order) return reply(404, { error: 'orderNotFound' });
    if (order.payment_status === 'paid') return reply(409, { error: 'alreadyPaid' });
    if (order.status !== 'awaiting_payment') return reply(409, { error: 'invalidState' });

    const { data: extra } = await admin.from('orders').select('payment_session_id, email, lang').eq('id', order.id).single();

    /* a retry closes the previous session first, so the same order can never be paid twice */
    if (extra?.payment_session_id) {
      try { await stripe(`/checkout/sessions/${extra.payment_session_id}/expire`); } catch { /* already completed/expired */ }
    }

    const session = await stripe('/checkout/sessions', {
      mode: 'payment',
      customer_email: extra?.email,
      client_reference_id: order.id,
      locale: LOCALES[extra?.lang ?? 'en'] ?? 'auto',
      line_items: { 0: { quantity: 1, price_data: { currency: order.currency.toLowerCase(), unit_amount: toMinor(order.total),
        product_data: { name: `Ozone Scents order ${order.id}` } } } },
      metadata: { order_id: order.id },
      payment_intent_data: { metadata: { order_id: order.id }, description: `Ozone Scents order ${order.id}` },
      success_url: `${SITE_URL}/order/${order.id}?new=1&paid=stripe`,
      cancel_url: `${SITE_URL}/checkout/payment?payment=cancelled`,
      expires_at: Math.floor(Date.now() / 1000) + 30 * 60          // Stripe minimum: 30 minutes
    }, { idempotencyKey: `${order.id}-${crypto.randomUUID()}` });

    await admin.from('orders').update({ payment_session_id: session.id, payment_provider: 'stripe' }).eq('id', order.id);
    return reply(200, { url: session.url });
  } catch (e) {
    console.error('stripe-checkout', order_id, (e as Error).message);
    return reply(502, { error: 'paymentProvider' });
  }
});

